apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nginx1
  namespace: dev
  labels:
    app: app-nginx1
spec:
    spec:
      containers:
      - name: app-nginx1
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nginx2
  namespace: dev
  labels:
    app: app-nginx2
spec: 
    spec:
      containers:
      - name: app-nginx2
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
